---
title: Bundestagswahl 2021
author: SPD Zürich
email: kontat@spd-zuerich.ch
description: "Eure Stimme bei der Bundestagswahl 2021: Informationen für Deutsche Staatsangehörige in der Schweiz"
baseurl: "/"
url: bundestagswahl.ch
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
