---
title: Bundestagswahl 2021
author: SPD Zürich
email: kontat@spd-zuerich.ch
description: Eine Informationsseite zur Bundestagswahl 2021 der SPD Zürich.
baseurl: "/"
url: bundestagswahl.ch
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
